config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  # get '/register/:user_id', to: 'users#new', as: 'new_user_referral'

  devise_for :adminstrators, path: 'admin',
   path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }

  namespace :admin do
      resources :transactions
      resources :users
      root to: "users#index"
    end

  devise_scope :user do
  root to: "devise/sessions#new"
  end

  devise_for :users

  get 'profile' => 'user#show', :as => 'profile'
  get 'deposit' => 'user#deposit', :as => 'deposit'
  get 'withdraw' => 'user#withdraw', :as => 'withdraw'
  get 'new_user_referral' => 'user#referral', :as => 'new_user_referral'

end

app/models/adminstrator.rb
class Adminstrator < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  validates :transaction_type, :amount, presence: true
  validates :transaction_type, inclusion: { in: %w[deposit withdraw] }
  validates :amount, numericality: { greater_than: 0 }

  after_save :handle_transaction

  private

  def handle_transaction
    case transaction_type
    when 'deposit'
      # user.update!(balance: user.balance + amount) if user.unique_id == unique_id
    when 'withdraw'
      user.update!(balance: user.balance - amount) if user.unique_id == unique_id && user.balance >= 300
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :transactions, foreign_key: 'user_id', dependent: :destroy
  has_one_attached :avatar
  attribute :balance, :decimal, default: 200
  attribute :bonus, :decimal, default: 200
  attribute :unique_id, :string, default: SecureRandom.hex(3)
  validates :balance, presence: true, numericality: { allow_decimal: true, greater_than: 0 }
  validates :firstname, :lastname, :username, :phone_number, presence: true
  validates :username, uniqueness: true
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_adminstrator!

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
    def after_sign_up_path_for(_resource)
      admin_root_path
    end

    def after_sign_in_path_for(_resource)
      admin_root_path
    end

    def after_sign_out_path_for(_resource)
      new_adminstrator_session_path
    end
  end
end

app/controllers/admin/transactions_controller.rb
module Admin
  class TransactionsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[firstname lastname username password phone_number])
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[email password])
  end

  def after_sign_up_path_for(_resource)
    profile_path
  end

  def after_sign_in_path_for(_resource)
    profile_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = current_user
    # @transactions = @user.transactions.includes(:user)
    # @user.avatar.attach(params[:avatar])
  end

  def deposit; end
  def withdraw; end
  def referral; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/user_helper.rb
module UserHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/admin/application/_navigation.html.erb
<%#
# Navigation

This partial is used to display the navigation in Administrate.
By default, the navigation contains navigation links
for all resources in the admin dashboard,
as defined by the routes in the `admin/` namespace
%>

<nav class="navigation navbar" role="navigation">
  <%= link_to(t("administrate.navigation.back_to_app"), root_url, class: "button button--alt button--nav") if defined?(root_url) %>

  <% Administrate::Namespace.new(namespace).resources_with_index_route.each do |resource| %>
    <%= link_to(
      display_resource_name(resource),
      resource_index_route(resource),
      class: "navigation__link navigation__link--#{nav_link_state(resource)}"
    ) if accessible_action?(model_from_resource(resource), :index)%>
  <% end %>
  <span class="logout-btn">
    <%= button_to "Logout", destroy_adminstrator_session_path, method: :delete, class:'bg-blue-600 text-white p-2'  %>
  </span>
</nav>

app/views/adminstrators/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/adminstrators/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class:"text-sm text-blue-500 hover:underline dark:text-blue-400" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class:"text-sm text-blue-500 hover:underline dark:text-blue-400" %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class:"text-sm text-blue-500 hover:underline dark:text-blue-400" %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name),class:"text-sm text-blue-500 hover:underline dark:text-blue-400" %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) ,class:"text-sm text-blue-500 hover:underline dark:text-blue-400"%><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTemplate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true  %> 
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body>
    <main class="relative">
      <p><%= notice%></p>
      <p><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_banner.erb
<div class="relative rounded-lg md:h-96">
      <img
        src="https://images.unsplash.com/photo-1619169412695-de792ce344e4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1480&q=80"
        class="w-full h-full object-fit"
        alt="..."
      />
      <div class="w-full h-full absolute top-0 left-0 right-0 bottom-0 bg-[#000000d0] flex    items-center justify-center p-10">
        <div class="text-white flex flex-col items-center justify-center gap-y-8">
          <div class="flex flex-col justify-center items-center gap-2">
            <h1 class="text-3xl md:text-6xl font-bold animate-slide-in text-center">
              Deposit and <span class="text-purple">Withdraw</span> Money
            </h1>
            <p class="text-1xl md:text-2xl text-gray-300 text-center">
              Choose from local payment methods, cards, E-wallet and more
            </p>
          </div>
          <%= link_to "Get Started", new_user_registration_path, class:"text-2xl md:text-3xl rounded-lg p-3 px-10 hover:opacity-90 active:bg-purple text-white bg-purple border border-purple"%>
        </div>
      </div>
</div>

app/views/shared/_contact.erb
<section class="bg-white dark:bg-gray-900">
    <div class="container px-6 py-12 mx-auto">
        <div>
            <p class="font-medium text-blue-500 dark:text-blue-400">Contact us</p>

            <h1 class="mt-2 text-2xl font-semibold text-gray-800 md:text-3xl dark:text-white">Chat to our friendly team</h1>

            <p class="mt-3 text-gray-500 dark:text-gray-400">We’d love to hear from you. Please fill out this form or shoot us an email.</p>
        </div>

        <div class="grid grid-cols-1 gap-12 mt-10 lg:grid-cols-2">
            <div class="grid grid-cols-1 gap-12 md:grid-cols-2">
                <div>
                    <span class="inline-block p-3 text-blue-500 rounded-full bg-blue-100/80 dark:bg-gray-800">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75" />
                        </svg>
                    </span>

                    <h2 class="mt-4 text-base font-medium text-gray-800 dark:text-white">Email</h2>
                    <p class="mt-2 text-sm text-gray-500 dark:text-gray-400">Our friendly team is here to help.</p>
                    <p class="mt-2 text-sm text-blue-500 dark:text-blue-400">hello@merakiui.com</p>
                </div>

                <div>
                    <span class="inline-block p-3 text-blue-500 rounded-full bg-blue-100/80 dark:bg-gray-800">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15 10.5a3 3 0 11-6 0 3 3 0 016 0z" />
                            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1115 0z" />
                        </svg>
                    </span>
                    
                    <h2 class="mt-4 text-base font-medium text-gray-800 dark:text-white">Live chat</h2>
                    <p class="mt-2 text-sm text-gray-500 dark:text-gray-400">Our friendly team is here to help.</p>
                    <p class="mt-2 text-sm text-blue-500 dark:text-blue-400">Start new chat</p>
                </div>

                <div>
                    <span class="inline-block p-3 text-blue-500 rounded-full bg-blue-100/80 dark:bg-gray-800">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15 10.5a3 3 0 11-6 0 3 3 0 016 0z" />
                            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1115 0z" />
                        </svg>
                    </span>
                    
                    <h2 class="mt-4 text-base font-medium text-gray-800 dark:text-white">Office</h2>
                    <p class="mt-2 text-sm text-gray-500 dark:text-gray-400">Come say hello at our office HQ.</p>
                    <p class="mt-2 text-sm text-blue-500 dark:text-blue-400">100 Smith Street Collingwood VIC 3066 AU</p>
                </div>

                <div>
                    <span class="inline-block p-3 text-blue-500 rounded-full bg-blue-100/80 dark:bg-gray-800">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 6.75c0 8.284 6.716 15 15 15h2.25a2.25 2.25 0 002.25-2.25v-1.372c0-.516-.351-.966-.852-1.091l-4.423-1.106c-.44-.11-.902.055-1.173.417l-.97 1.293c-.282.376-.769.542-1.21.38a12.035 12.035 0 01-7.143-7.143c-.162-.441.004-.928.38-1.21l1.293-.97c.363-.271.527-.734.417-1.173L6.963 3.102a1.125 1.125 0 00-1.091-.852H4.5A2.25 2.25 0 002.25 4.5v2.25z" />
                        </svg>
                    </span>
                    
                    <h2 class="mt-4 text-base font-medium text-gray-800 dark:text-white">Phone</h2>
                    <p class="mt-2 text-sm text-gray-500 dark:text-gray-400">Mon-Fri from 8am to 5pm.</p>
                    <p class="mt-2 text-sm text-blue-500 dark:text-blue-400">+1 (555) 000-0000</p>
                </div>
            </div>

            <div class="p-4 py-6 rounded-lg bg-gray-50 dark:bg-gray-800 md:p-8">
                <form>
                    <div class="-mx-2 md:items-center md:flex">
                        <div class="flex-1 px-2">
                            <label class="block mb-2 text-sm text-gray-600 dark:text-gray-200">First Name</label>
                            <input type="text" placeholder="John " class="block w-full px-5 py-2.5 mt-2 text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-lg dark:placeholder-gray-600 dark:bg-gray-900 dark:text-gray-300 dark:border-gray-700 focus:border-blue-400 dark:focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40" />
                        </div>

                        <div class="flex-1 px-2 mt-4 md:mt-0">
                            <label class="block mb-2 text-sm text-gray-600 dark:text-gray-200">Last Name</label>
                            <input type="text" placeholder="Doe" class="block w-full px-5 py-2.5 mt-2 text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-lg dark:placeholder-gray-600 dark:bg-gray-900 dark:text-gray-300 dark:border-gray-700 focus:border-blue-400 dark:focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40" />
                        </div>
                    </div>

                    <div class="mt-4">
                        <label class="block mb-2 text-sm text-gray-600 dark:text-gray-200">Email address</label>
                        <input type="email" placeholder="johndoe@example.com" class="block w-full px-5 py-2.5 mt-2 text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-lg dark:placeholder-gray-600 dark:bg-gray-900 dark:text-gray-300 dark:border-gray-700 focus:border-blue-400 dark:focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40" />
                    </div>

                    <div class="w-full mt-4">
                        <label class="block mb-2 text-sm text-gray-600 dark:text-gray-200">Message</label>
                        <textarea class="block w-full h-32 px-5 py-2.5 mt-2 text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-lg md:h-56 dark:placeholder-gray-600 dark:bg-gray-900 dark:text-gray-300 dark:border-gray-700 focus:border-blue-400 dark:focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40" placeholder="Message"></textarea>
                    </div>

                    <button class="w-full px-6 py-3 mt-4 text-sm font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-blue-500 rounded-lg hover:bg-blue-400 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-50">
                        Send message
                    </button>
                </form>
            </div>
        </div>
    </div>
</section>

app/views/shared/_header.erb
<% resource = User.new %> <!-- Define the Devise resource variable -->
<% resource_name = :user %> <!-- Define the Devise resource name -->
<header class="bg-purple p-3 w-full">
	<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
		<div class="flex gap-2">
			<div class="w-2/5">
				<%= f.email_field :email, autofocus: true, autocomplete: "email", class:"w-full rounded-md placeholder-purple border border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 mb-2", placeholder:"Username...",value: resource.email %>
				<%= link_to "Forgot password?", new_user_password_path, class: "text-orange-600" %>
			</div>
			<div class="w-2/5">
				<%= f.password_field :password , placeholder:"Password...", class:"w-full rounded-md p-2
				placeholder-purple mb-2", value: resource.password %>
				<p class="text-white text-[14px]">Input correct passowrd</p>
			</div>
			<div class="flex flex-col gap-2 w-1/4">
			<input type="submit" value="Login" , class="text-white bg-green p-2 cursor-pointer border border-3 border-green rounded-md">
				<%= link_to "Register", new_user_registration_path, class: "w-full text-white bg-green p-2 cursor-pointer border-gray-100 rounded-md flex justify-center items-center border-3 border-green"%>
			</div>
		</div>
	  <%end%>
</header>

app/views/shared/_nav.erb
<nav class="bg-white p-3 items-center justify-center">
	<%= link_to "Home", root_path%>
</nav>

app/views/shared/_resetpassword.erb
<section class="bg-white dark:bg-gray-900">
    <div class="container flex flex-col items-center justify-center min-h-screen px-6 mx-auto">
        <div class="flex justify-center mx-auto">
            <img class="w-auto h-7 sm:h-8" src="https://merakiui.com/images/logo.svg" alt="">
        </div>

        <h1 class="mt-4 text-2xl font-semibold tracking-wide text-center text-gray-800 capitalize md:text-3xl dark:text-white">
            welcome Back
        </h1>

        <div class="flex items-center mt-6">
            <p class="text-gray-500 dark:text-gray-400">continue as</p>

            <div class="flex items-center mx-2">
                <img class="object-cover w-8 h-8 mx-1 rounded-full" src="https://images.unsplash.com/photo-1628890923662-2cb23c2e0cfe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80" alt="">
                <span class="mx-1 text-gray-800 dark:text-white">Ana Williams...</span>
            </div>

            <button class="text-blue-500 dark:text-blue-400 focus:outline-none hover:underline">change</button>
        </div>

        <div class="w-full max-w-md mx-auto mt-6">
            <form>
                <div>
                    <label class="block mb-2 text-sm text-gray-600 dark:text-gray-200">Password</label>
                    <input type="password" placeholder="Enter your password" class="block w-full px-5 py-3 mt-2 text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-lg dark:placeholder-gray-600 dark:bg-gray-900 dark:text-gray-300 dark:border-gray-700 focus:border-blue-400 dark:focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40" />
                </div>

                <a href="#" class="inline-block mt-4 text-blue-500 capitalize hover:underline dark:text-blue-400">
                    reset password?
                </a>

                <button class="w-full px-6 py-3 mt-4 text-sm font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-blue-500 rounded-lg hover:bg-blue-400 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-50">
                    “Continue”
                </button>

                <div class="mt-6 text-center">
                    <a href="#" class="text-sm text-blue-500 hover:underline dark:text-blue-400">
                        Don’t have an account yet? Sign up
                    </a>
                </div>

                <p class="mt-6 text-gray-500 dark:text-gray-400">
                    By clicking “Continue” above, you acknowledge that you have read and
                    understood, and agree to Our <a href="#" class="text-gray-700 dark:text-white">Term & Conditions</a>
                    and<a href="#" class="text-gray-700 dark:text-white"> Privacy Policy.</a>
                </p>
            </form>
        </div>
    </div>
</section>

app/views/user/_navbar.erb
<nav class="bg-purple md:px-2 py-2 relative">
		<div class="flex flex-wrap items-center justify-between p-2">

			<p class="flex flex-col px-4 py-2 font-bold text-1xl text-center text-white">
				User Id <span><%= @user.unique_id%></span>
			</p>
				
			<ul
				class = "flex text-1xl md:text-[18px]
				px-2 gap-3  text-white justify-center items-center" 
			>
			
				<li class="w-full hover:bg-gray-600 active:bg-gray-700 md:active:bg-transparent md:hover:bg-transparent text-center duration-75 rounded-md">
					<p class="block px-4 py-2  font-bold text-1xl">
						Balance <span class="block">R <%= @user.balance%> </span>
					</p>
				</li>
				<li class="w-full hover:bg-gray-600 active:bg-gray-700 md:active:bg-transparent md:hover:bg-transparent text-center duration-75 rounded-md">
					<p class="block px-4 py-2  font-bold text-1xl">
						Bonus <span class="block">R <%= @user.bonus%> </span>
					</p>
				</li>
		</ul>

		<div>

			<div>
      <button class="relative group harmbugger">
        <div class="relative flex overflow-hidden items-center justify-center rounded-full w-[50px] h-[50px] transform transition-all bg-slate-700 ring-0 ring-gray-300 hover:ring-8 group-focus:ring-4 ring-opacity-30 duration-200 shadow-md">
          <div class="flex flex-col justify-between w-[20px] h-[20px] transform transition-all duration-300 overflow-hidden">
            <div class="bg-white h-[2px] w-7 transform transition-all  group-focus:w-2/3 delay-150"></div>
            <div class="bg-white h-[2px] w-7 rounded transform transition-all duration-300"></div>
            <div class="bg-white h-[2px] w-7 transform transition-all duration-300 group-focus:w-2/3 delay-150"></div>
          </div>
        </div>
      </button>
    </div>

			<div class="absolute right-0 z-10 mt-2 w-56 origin-top-right divide-y divide-gray-100 rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none hidden menu duration-100" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
     <div class="py-1" role="none">
      <span class="text-gray-700 block px-4 py-2 text-sm hover:bg-gray-200 hover:text-white" role="menuitem" tabindex="-1", id="menu-item-2"><%= link_to "Edit Profile", edit_user_registration_path %></span>
    </div>
		<div cl	ass="py-1" role="none">
      <span class="text-gray-700 block px-4 py-2 text-sm hover:bg-gray-200 hover:text-white" role="menuitem" tabindex="-1", id="menu-item-2"><%= link_to "Refer A Friend", new_user_referral_path %></span>
    </div>
    <div class="py-1" role="none">
      <span class="text-gray-700 block px-4 py-2 text-sm hover:bg-gray-200 hover:text-white" role="menuitem" tabindex="-1", id="menu-item-2"><%= link_to "Deposit", deposit_path %></span>
    </div>
     <div class="py-1" role="none">
      <span class="text-gray-700 block px-4 py-2 text-sm hover:bg-gray-200 hover:text-white" role="menuitem" tabindex="-1", id="menu-item-2"><%= link_to "Withdraw", withdraw_path %></span>
    </div>
    <div class="py-1" role="none">
      <span class="text-gray-700 block px-4 py-2 text-sm hover:bg-gray-200 hover:text-white" role="menuitem" tabindex="-1", id="menu-item-2"><%= button_to "Logout", destroy_user_session_path, method: :delete %></span>
    </div>
  </div>
	</div>
</nav>